In [8]:
import pandas as pd
from numpy.random import logistic
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split

In [9]:
from sklearn.datasets import load_digits
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [21]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

/Users/abhi/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9694444444444444

In [22]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9944444444444445

In [23]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9722222222222222

In [24]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [25]:
kf.split(x_train,y_train)

<generator object _BaseKFold.split at 0x1770d2df0>

In [26]:
def get_score(model,x_train,y_train,x_test,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [38]:
get_score(rf,x_train,y_train,x_test,y_test)

0.9722222222222222

In [39]:
get_score(lr,x_train,y_train,x_test,y_test)

/Users/abhi/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9694444444444444

In [35]:
get_score(svm,x_train,y_train,x_test,y_test)

0.9944444444444445

In [40]:
get_score(SVC(),x_train,y_train,x_test,y_test)

0.9944444444444445

In [42]:
get_score(DecisionTreeClassifier(),x_train,y_train,x_test,y_test)

0.8472222222222222

In [49]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)

In [50]:
for a,b in kf.split([2,3,4,5,6]):
    print(a,b)

[2 3 4] [0 1]
[0 1 3 4] [2]
[0 1 2 4] [3]
[0 1 2 3] [4]


In [74]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=4)
skf

StratifiedKFold(n_splits=4, random_state=None, shuffle=False)

In [75]:
score_lr=[]
score_svm=[]
score_rf=[]
import numpy as np

In [76]:
for train_index,test_index in skf.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_lr.append(get_score(lr,x_train,y_train,x_test,y_test))
    score_svm.append(get_score(svm,x_train,y_train,x_test,y_test))
    score_rf.append(get_score(rf,x_train,y_train,x_test,y_test))


/Users/abhi/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/abhi/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.h

In [78]:
print(sum(score_lr)/len(score_lr))

0.9265392229646128


In [79]:
print(sum(score_rf)/len(score_rf))

0.9426787923781242


In [80]:
print(sum(score_svm)/len(score_svm))

0.9654998762682504


No need to write the above long code, Just do following:

In [13]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_digits
digits = load_digits()


In [19]:
from sklearn.svm import SVC

In [21]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])